cognisant/Docs.DevelopmentProcess

Source Control.md

Added full stops on bullet points.
Changed below to above.

Punctuation and word change

---

.gitignore
README.md
docs/source-control.md

Applied prettier to all files to prevent future issues when writing documentation.

Apply prettier to files.

---

README.md
docs/code-style/javascript.md

Only question I have based on updating this is our usage of the AirBnB editor config. I've currently included the Prettier config from the guide linked, however Prettier will use the information in an editor config so we could rely on that. The only thing I don't like about the AirBnb editor config is the lack of line length limit.

Updated JS docs

---

README.md

Should the prioritisation section be moved to later in the file?

Epics and Prioritisation

---

README.md

The preview doesn't seem to reflect the change accurately.

Adjusted Business Review's whitespace

---

README.md

I think the text added is necessary to explain what a card is for.

Added more detail to Discovery

---

docs/code-style/javascript.md

- Updated the JS Codestyles to mention installing `eslint-loader`
- Updated the JS Codestyles to include adding a `.gitattributes` file to ensure line endings are correct when checked out from git.

Update js codestyles

---

README.md

Updated the description of tech debt to reflect the current process.

Updated description of tech debt

---

README.md

Added content to describe how retrospective goals are tracked on the sprint board.

Retrospective Goals Documentation

---

README.md

Re-ordered and slightly re-worded the description of the review process.

Review process description tweak

---

README.md

Documented that estimated effort includes getting stories to 'done'.

Estimation section mentions definition of done

---

README.md

Added content describing how the team tracks support tickets.

Information about support ticket tracking

---

README.md

* Re-ordered analysis of a card and voting on it (now vote then explain)
* Added content describing how the team attempts to break down a story after a 21 vote

Updated estimation info to reflect the current process

---

README.md

Added content describing what a priority story is and how they can be identified.

Added information about priority stories

---

README.md

Added content describing the 'Sprint Velocity' and 'Time Breakdowns' Google sheets, and how they are used.

Scrum Spreadsheets Documentation

---

README.md

Mentioned that team members should consider pairing/parallelising work before looking at a new story.

'help others before starting a new story'

---

README.md

- The definition of done section has been updated to include information on the technical documentation that may need to be updated.

Updated Definition of Done

---

README.md

- Distraction Review has been moved to retrospective section.
- Information about identifying improvements based on distractions has been added.

Updated Distraction Review

---

README.md
docs/ceremony-agenda/backlog-refinement.md

(Combination of demo and BLR agenda docs, BLR has already been merged, the demo PR was previously approved)

More ceremony agenda

---

docs/ceremony-agenda/retrospective.md
docs/ceremony-agenda/sprint-kick-off.md

(https://trello.com/c/sRzuaWzT)

Moved achievement recording to sprint start doc

---

docs/ceremony-agenda/daily-scrum.md

(https://trello.com/c/IoqOcTw8)

Combined last 3 questions
